name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Generate Snake animation
        uses: Platane/snk@master
        with:
          github_user_name: Amanda-N-Andrade 
          outputs: "github-snake.svg"
      
      - name: Push Snake animation to the output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          force: true
          directory: "."

      - name: Generate Snake animation image URL
        run: |
          echo "Image URL: ![Snake animation](https://raw.githubusercontent.com/Amanda-N-Andrade/Amanda-N-Andrade/output/snake.svg)"
